# Generated by Django 5.2.16 on 2026-07-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
